AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda function to import cloudtrail into elasticsearch.
Resources:
  s3CT2ES:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: s3CT2ES/lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::111111111111:role/service-role/YourLambdaRole'
      Environment:
        Variables:
          "ES_INDEX": "cloudtrail"
          "ES_HOST": "search-yourdomain.eu-west-1.es.amazonaws.com"
